### ISSUE TITLE
Doesn't build with base64-bytestring 1.1.0.0

### ISSUE THREAD

**Issue by felixonmars** [jgm/ipynb#1]
```
[1 of 1] Compiling Data.Ipynb       ( src/Data/Ipynb.hs, dist/build/Data/Ipynb.dyn_o )

src/Data/Ipynb.hs:486:36: error:
    Not in scope: ‘Base64.joinWith’
    Module ‘Data.ByteString.Base64’ does not export ‘joinWith’.
    |
486 |           toJSON $ TE.decodeUtf8 . Base64.joinWith "\n" 76 . Base64.encode $ bs
    |                                    ^^^^^^^^^^^^^^^
```

They have removed `joinWith` in https://github.com/haskell/base64-bytestring/pull/32

**Comment by jgm** [comment]
Just pushed a fix for this!
